### ISSUE TITLE
Distribute via chrome too

### ISSUE THREAD

**Issue by thehereward** [hgcummings/aoc-deltarank#1]
I've tested this extension against Chrome using DevTools and it Just Works.

Do you have time/willingness to add it to Chrome too? Or are you happy for me to do that?

The [instructions](https://developer.chrome.com/docs/extensions/mv3/hosting/) look pretty trivial (assuming you have Chrome installed).

**Comment by hgcummings** [comment]
Yes, it does indeed "just work" in Chrome. I submitted it to their store on Friday but they're being a bit slower to review it than Mozilla were. It should be up there soon.

**Comment by thehereward** [comment]
Wonderful! Sorry, didn't realise you were already on top of it. :-)

**Comment by hgcummings** [comment]
This has been published now: https://chrome.google.com/webstore/detail/advent-of-code-delta-rank/meifppogcngbljnpnhpokdblbghfdmce
